spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/saas_sports
spring.datasource.username=saas_user
spring.datasource.password=saas_password
spring.jpa.hibernate.ddl-auto=update